apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music-quota
  labels:
    app: spring-music-quota
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-music-quota
  template:
    metadata:
      labels:
        app: spring-music-quota
    spec:
      containers:
      - name: spring-music-quota
        image: tanzuregistry.azurecr.io/spring-music
        resources:
          requests:
            memory: "1G"
            cpu: "100m"
          limits:
            memory: "2G"
            cpu: "500m"
      imagePullSecrets:
      - name: tanzuregistry-secret
