apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music-security
  labels:
    app: spring-music-security
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-music-security
  template:
    metadata:
      labels:
        app: spring-music-security
    spec:
      containers:
      - name: spring-music-security
        image: tanzuregistry.azurecr.io/spring-music
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
        securityContext:
          allowPrivilegeEscalation: true
      volumes:
      - name: sec-ctx-vol
        emptyDir: {}
      imagePullSecrets:
      - name: tanzuregistry-secret